### ISSUE TITLE
failing to segment ts stream of ATSC broadcast using output of dvbv5-zap on rpi3

### ISSUE THREAD

**Issue by grkblood13** [jordicenzano/go-ts-segmenter#9]
I can build the program and run it, but I don't get any output. Running in verbose mode:

cat /home/alarm/local-channels/pipe.ts | ./bin/manifest-generator -f "chunk_" -t 1 -v

I get the following output. Please let me know what more information you need.

{"level":"info","msg":"1.1.00x20a2630","time":"2020-04-19T08:43:45-05:00"}
{"level":"info","msg":"Started tssegmenter0x20a2630","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:11 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:
false SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fa
lse}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:12 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:
false SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fa
lse}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:true TransportPriority:false PID:52 TransportScramblingControl:0 AdaptationFieldC
ontrol:1 ContinuityCounter:14 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:f
alse SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fal
se}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:13 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:
false SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fa
lse}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:14 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:
false SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fa
lse}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:15 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:
false SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fa
lse}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"OTHER: {valid:true SyncByte:71 TransportErrorIndicator:false PayloadUnitStartIndicator:false TransportPriority:false PID:49 TransportScramblingControl:0 AdaptationField
Control:1 ContinuityCounter:0 AdaptationField:{AdaptationFieldLength:0 DiscontinuityIndicator:false RandomAccessIndicator:false ElementaryStreamPriorityIndicator:false PCRFlag:false OPCRFlag:f
alse SplicingPointFlag:false TransportPrivateDataFlag:false AdaptationFieldExtensionFlag:false PCRData:{ProgramClockReferenceBase:0 reserved:0 ProgramClockReferenceExtension:0 PCRs:0 valid:fal
se}} Pat:{valid:false PmtPID:0} Pmt:{valid:false Videoh264:[] AudioADTS:[] Other:[]}}","time":"2020-04-19T08:43:45-05:00"}
{"level":"debug","msg":"Sent to process: 128 bytes","time":"2020-04-19T08:43:45-05:00"}

...

**Comment by jordicenzano** [comment]
It would be great if you can upload somewhere few MB of that transport stream

**Comment by grkblood13** [comment]
here ya go: https://file.io/aeJmUM7X

**Comment by jordicenzano** [comment]
The uploaded file is mpeg2 video and EC3 audio, this code only works for h264 and ADTS. Feel free to fork and update the code
